language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - jruby
  - rbx
before_install:
  - rvm uninstall jruby
  - rvm use jruby-1.7.18 --install
script: bundle exec rspec spec && bundle exec cucumber --tag ~@wip
sudo: false
